### PR TITLE
Add support for Lombok's @Builder.Default

### PR DESCRIPTION
**Pull request by MehrunesSky**
Hello, 

I would like to add default values in JIlt without having to specify them in my constructor. 
So I thought of an @Builder.Default annotation a bit like lombok, which takes the default value as a parameter. 
This is just a suggestion. If you have any feedback or another idea for implementing this, please don't hesitate to contact me.

### CODE REVIEW

**Comment by skinny85** [comment]
Hi @MehrunesSky,

Thanks for submitting the PR!

Before I review it in depth, can you share more about the use case here? In what situation would you want to have a default value only in the Builder, and not in the constructor of your class?

Thanks,
Adam

**Comment by MehrunesSky** [comment]
Hello, 

I have very large objects and jilt allows me to easily instantiate them with properties that are optional and others that are not. 
But as a consequence, my constructor is very consequent just because I have to manage default values (like initialized with empty collections for example). I'd like to use lombok's @AllArgsConstructor and if I'd used lombok's @Builder, I'd have used @Builder.Default.
And that's the functionality I'd like with Jilt, to be able to indicate that if an attribute hasn't been entered, then I take the default value. 

I don't know if it's clear, please don't hesitate if I need to clarify.

**Comment by skinny85** [comment]
Thanks for the explanation! I suspected this is related to some Lombok BS 😉.

I was thinking of a slightly different design for this feature 🙂. Since having a default value implies the property is optional, I wouldn't introduce a new annotation just for this, but instead use the existing `@Opt` annotation.

Another part I'm not super enthusiastic about is the initializer being inside a string. I'd much rather prefer if it was regular code.

Given that, how about we change the implementation to instead take the Builder initializer from the field initializer, same way as Lombok's `@Builder.Default` works?

So, something like this:

```java
import lombok.AllArgsConstructor;
import org.jilt.Builder;
import org.jilt.Opt;

@AllArgsConstructor
@Builder
public final class MyClass {
    @Opt
    private String field = initializeMe();

    // ...
}
```

This would result in `field` being initialized with `initializeMe()` in `MyClassBuilder`.

Alternatively, if you're worried about this change not being backwards compatible, I would also accept special-casing the treatment of Lombok's `@Builder.Default` instead of introducing our own. We would treat all fields annotated with `@lombok.Builder.Default` as implicitly optional, similarly like we do for `@Nullable` annotations today, and we would copy over the initializer to the Builder, so it would look something like:

```java
import lombok.AllArgsConstructor;
import lombok.Builder.Default;
import org.jilt.Builder;

@AllArgsConstructor
@Builder
public final class MyClass {
    @Default
    private String field = initializeMe();

    // ...
}
```

Let me know what you think of these ideas!

**Comment by MehrunesSky** [comment]
It's a great idea to use lombok's Builder.Default. 
I had thought of using the annotated field initializer, but I don't really see how to implement it. 

Do you have any advice on how to implement it? Using a third-party dependency like ASM or Javassist? Or I'm thinking of initializing the Class and retrieving the value by reflection, but that seems a bit complex. 

I've never really used Java reflexion, so it's quite new for me to contribute to a code generation project.

**Comment by skinny85** [comment]
I would just copy the initializer code as-is, and make sure to clarify in the documentation that you have to use fully-qualified names if you use anything that requires an import (like your example with `Collections.emptySet()` in the test) 🙂.

**Comment by MehrunesSky** [comment]
But how do you copy the initializer as-is without external dependencies? Is there a technique? Do you have an example?

**Comment by MehrunesSky** [comment]
I don't quite understand.
To sum up, you have to use the @lombok.Builder.Default annotation and take the default initializer.

So if the class is like this : 
```java
@AllArgsConstructor
@Builder
public final class MyClass {
    @lombok.Builder.Default
    private String field = initializeMe();

    // ...
}
```


The builder will look something like this: 


```java
public final class MyClassBuilder {

    private String field = initializeMe();

    // ...
}
```


But I can't see how to technically copy the initializeMe() to the builder. I don't think I can just grab the “initializeMe();” with the java api.
I'm really sorry I'm having trouble understanding.

**Comment by MehrunesSky** [comment]
Okay, I understand better. But do you have any idea how to implement your proposal? It seems very complicated to implement.

**Comment by skinny85** [comment]
Why? 🙂 Like I said before, just copy the initializer as-is from the class to the Builder, and you're done 🙂.

File: src/main/java/org/jilt/internal/TypeSafeUngroupedOptionalsBuilderGenerator.java [hunk 1]
```diff
@@ -18,10 +19,10 @@
 
 final class TypeSafeUngroupedOptionalsBuilderGenerator extends AbstractTypeSafeBuilderGenerator {
     TypeSafeUngroupedOptionalsBuilderGenerator(TypeElement targetClass, List<? extends VariableElement> attributes,
-            Builder builderAnnotation, BuilderInterfaces builderInterfaces,
-            ExecutableElement targetCreationMethod, Elements elements, Filer filer) {
+                                               Builder builderAnnotation, BuilderInterfaces builderInterfaces,
+                                               ExecutableElement targetCreationMethod, Elements elements, Trees trees, Filer filer) {
```
Comment (skinny85) [inline src/main/java/org/jilt/internal/TypeSafeUngroupedOptionalsBuilderGenerator.java:23]: Same here:

```suggestion
            Builder builderAnnotation, BuilderInterfaces builderInterfaces,
            ExecutableElement targetCreationMethod, Elements elements, Trees trees, Filer filer) {
```

File: src/test/java/org/jilt/test/data/defaultvalue/DefaultValueWithLombok.java [hunk 2]
```diff
@@ -0,0 +1,39 @@
+package org.jilt.test.data.defaultvalue;
+
+import org.jilt.Builder;
+
+import java.util.Set;
+
+@Builder
+public class DefaultValueWithLombok {
```
Comment (skinny85) [inline src/test/java/org/jilt/test/data/defaultvalue/DefaultValueWithLombok.java:8]: Let's add `@AllArgsConstructor` here too, instead of writing the constructor by hand.

File: src/test/java/org/jilt/test/data/defaultvalue/DefaultValueWithLombok.java [hunk 3]
```diff
@@ -0,0 +1,39 @@
...
+
+    @lombok.Builder.Default
```
Comment (skinny85) [inline src/test/java/org/jilt/test/data/defaultvalue/DefaultValueWithLombok.java:10]: Let's add an import for `lombok.Builder.Default` instead of using the fully qualified name.

File: src/test/java/org/jilt/test/data/defaultvalue/DefaultValueWithLombok.java [hunk 4]
```diff
@@ -0,0 +1,39 @@
...
+    public String attr2 = "attr2";
+
+    @lombok.Builder.Default
+    public boolean attr3 = true;
+
+    public int attr4 = 1000;
+
+    @lombok.Builder.Default
+    public int attr5 = 1000;
```
Comment (skinny85) [inline src/test/java/org/jilt/test/data/defaultvalue/DefaultValueWithLombok.java:22]: Let's try referencing the field here, to check if that works? So something like

```suggestion
    public int attr5 = attr1 + 1000;
```

File: src/test/java/org/jilt/test/data/defaultvalue/DefaultValueWithOpt.java [hunk 5]
```diff
@@ -0,0 +1,40 @@
...
+import org.jilt.Builder;
+import org.jilt.Opt;
+
+import java.util.Set;
+
+@Builder
+public class DefaultValueWithOpt {
+
+    @Opt
+    public int attr1 = 1;
```
Comment (skinny85) [inline src/test/java/org/jilt/test/data/defaultvalue/DefaultValueWithOpt.java:12]: Let's not implement this functionality for `@Opt`. Let's make it work only for `@lombok.Builder.Default`.

I would remove this entire class.

File: src/test/java/org/jilt/test/data/defaultvalue/DefaultValueWithLombok.java [hunk 6]
```diff
@@ -0,0 +1,39 @@
+package org.jilt.test.data.defaultvalue;
+
+import org.jilt.Builder;
+
+import java.util.Set;
+
+@Builder
+public class DefaultValueWithLombok {
+
```
Comment (skinny85) [inline src/test/java/org/jilt/test/data/defaultvalue/DefaultValueWithLombok.java:9]:
```suggestion
```

File: src/test/java/org/jilt/test/data/defaultvalue/DefaultValueWithLombok.java [hunk 7]
```diff
@@ -0,0 +1,39 @@
+package org.jilt.test.data.defaultvalue;
+
+import org.jilt.Builder;
+
+import java.util.Set;
+
+@Builder
```
Comment (skinny85) [inline src/test/java/org/jilt/test/data/defaultvalue/DefaultValueWithLombok.java:7]: This PR is missing the functionality of marking a field annotated with `@lombok.Builder.Default` as optional. We would catch it if we made the `@Builder` here `STAGED`.

So, let's change this to:

```suggestion
@Builder(style = BuilderStyle.STAGED)
```

and make sure the `DefaultTest ` test still passes.

File: src/test/java/org/jilt/test/DefaultTest.java [hunk 8]
```diff
@@ -0,0 +1,51 @@
...
+import org.jilt.test.data.defaultvalue.DefaultValueWithLombokBuilder;
+import org.jilt.test.data.defaultvalue.DefaultValueWithOpt;
+import org.jilt.test.data.defaultvalue.DefaultValueWithOptBuilder;
+import org.junit.Test;
+
+import java.util.Collections;
+
+import static org.assertj.core.api.Assertions.assertThat;
+
+public class DefaultTest {
```
Comment (skinny85) [inline src/test/java/org/jilt/test/DefaultTest.java:13]: Let's call this class `LombokDefaultTest`, or something like that, instead.

**Review by skinny85 — COMMENTED** [review]
Thanks a lot for the new revision @MehrunesSky! I have a few comments, most importantly, we need to make sure that, if a field is annotated with `@lombok.Builder.Default`, it is treated as optional (same as if it was annotated with `@Opt`).

File: build.gradle [hunk 9]
```diff
@@ -100,6 +100,7 @@ dependencies {
     compileOnly 'com.squareup:javapoet:1.8.0'
 
     testImplementation 'junit:junit:4.13.2'
+    testImplementation 'org.projectlombok:lombok:1.18.36'
```
[the remark this answers is not in the document]
Comment (MehrunesSky) [reply build.gradle:104]: It's fix :)

File: src/test/java/org/jilt/test/data/defaultvalue/DefaultValueWithLombok.java (hunk 2 above)
Comment (MehrunesSky) [reply src/test/java/org/jilt/test/data/defaultvalue/DefaultValueWithLombok.java:12]: It's fix :)

File: src/main/java/org/jilt/internal/AbstractBuilderGenerator.java [hunk 10]
```diff
@@ -113,6 +127,24 @@ public final void generateBuilderClass() throws Exception {
...
+                .anyMatch(a -> "lombok.Builder.Default".equals(a.getAnnotationType().asElement().toString()));
+    }
+
+    private CodeBlock getCodeBlockInitializer(VariableElement attribute) {
+        Tree tree = trees.getPath(attribute).getLeaf();
+        String initializer = "";
+        if (tree instanceof VariableTree && ((VariableTree) tree).getInitializer() != null) {
+            initializer = ((VariableTree) tree).getInitializer().toString();
+        }
+        return initializer.isEmpty()? CodeBlock.of("") : CodeBlock.of("$L", initializer);
```
[the remark this answers is not in the document]
Comment (MehrunesSky) [reply src/main/java/org/jilt/internal/AbstractBuilderGenerator.java:148]: Yes indeed, I could make it fail if there's no initialization. 

If you know of an easier way to do this, I'd love to hear about it, but I've been doing a lot of searching on the internet and came across this. 
getLeaf retrieves the syntactic representation of the variable. VariableTree represents the variable's syntactic node.

Unfortunately, I couldn't find a simpler way of doing this, and the problem with this code is that to use Tree tree = trees.getPath(attribute).getLeaf();, you need to be in a java version higher than java 8 (I wasn't able to test in java 9).

File: build.gradle (hunk 9 above)
[the remark this answers is not in the document]
Comment (skinny85) [reply build.gradle:104]: Do we need Lombok in both `testImplementation` and `testAnnotationProcessor`? Isn't `testAnnotationProcessor` enough?

File: src/main/java/org/jilt/internal/AbstractBuilderGenerator.java (hunk 10 above)
[the remark this answers is not in the document]
Comment (skinny85) [reply src/main/java/org/jilt/internal/AbstractBuilderGenerator.java:148]: OK. For now, let's just leave it as-is. We'll figure out how to deal with this later (most likely, we'll reproduce whatever this does, just only for fields, since we don't care about other element kinds).

Can you remove Java 8 from [here](https://github.com/skinny85/jilt/blob/5566380bffb7a4234d03167a7c35840df64eb265/.github/workflows/build.yaml#L10-L10) temporarily, so that we can see whether the build passes for Java 9+?

**Comment by skinny85** [comment]
@MehrunesSky is this functionality something you still need? I'd be happy to take over the PR, but only if there's still interested behind it 🙂.

**Comment by MehrunesSky** [comment]
> @MehrunesSky is this functionality something you still need? I'd be happy to take over the PR, but only if there's still interested behind it 🙂.

Yes, sorry, I had to take a break on this PR for a priority and I forgot to come back to it, but I'm still interested in this feature, so I'll commit it soon and apply your feedback.
Sorry for the delay

**Comment by skinny85** [comment]
> > @MehrunesSky is this functionality something you still need? I'd be happy to take over the PR, but only if there's still interested behind it 🙂.
> 
> Yes, sorry, I had to take a break on this PR for a priority and I forgot to come back to it, but I'm still interested in this feature, so I'll commit it soon and apply your feedback. Sorry for the delay

No worries, we are all doing this in our spare time, so this is completely understandable 🙂.

Don't worry about updating the code with my feedback - I actually looked at this issue this weekend, and figured out how to make it work for Java 8 as well. Since you the left the `Maintainers are allowed to edit this pull request` at the default checked value, I'll just update the code in this PR with my branch.

**Comment by skinny85** [comment]
@MehrunesSky I've pushed an update, and the build succeeded.

Let me know if this code makes sense to you!

**Comment by MehrunesSky** [comment]
Yes it's perfect, I didn't know that just adding the tools.jar from home would have worked.
Maybe just add a test in case you put an @Opt with @Default on the same field, no?

**Comment by skinny85** [comment]
> Yes it's perfect, I didn't know that just adding the tools.jar from home would have worked.

👍

> Maybe just add a test in case you put an @opt with @default on the same field, no?

Sure, I can add that, but curious why do you think it’s needed?

**Comment by skinny85** [comment]
OK, you've convinced me 🙂. Added.

**Comment by MehrunesSky** [comment]
For me, it's very clear, and the little note about lombok warnings when using @Default without @lombok.Builder is really interesting.

**Comment by skinny85** [comment]
Thanks. But I just realized I forgot to mention the "no import" part of the initializer in the documentation. I'll update it.

**Comment by skinny85** [comment]
Thanks a lot for submitting the PR @MehrunesSky!

**Comment by skinny85** [comment]
Hey @MehrunesSky,

I've released a preview version including the changes from this PR: [version `1.8.rc1`](https://search.maven.org/artifact/cc.jilt/jilt/1.8.rc1/jar).

Can you try it in your project, and let me know if it works correctly?

Thanks,
Adam

**Comment by skinny85** [comment]
Hey @MehrunesSky,

from my testing, I've unfortunately found a problem with Jilt's Lombok support, and it's related to the `@Data` and `@Value` annotations.

The issue is that, when using `@lombok.Builder.Default` on a final field (all fields are final in `@Value`, and the same problem happens with `@Data`, because if you don't mark a field as `final` with `@Data`, it will have a setter generated, which is typically not what you want when using Builders), Lombok actually removes the field initializer from the code after copying it to its own Builder!

This makes some sense, because if a `final` field has an initializer, you cannot re-assign it in the class's constructor, which would make that field always have the value from the initializer, which is not what you want. So, Lombok effectively "hijacks" the initializer in this case to serve as the Builder default value.

As a consequence of this, if Lombok runs as the first annotation processor before Jilt, the `@lombok.Builder.Default` field will no longer have the initializer present, and thus Jilt will have nothing to set on its Builder. And, [you cannot specify which order annotation processors run in](https://stackoverflow.com/a/29206412) 😕. So, it might accidentally work in one project, because Jilt happens to run before Lombok, but not in the other, with the same code! That seems like a nightmare to debug.

This makes Jilt's support for `@lombok.Builder.Default` basically unusable when combined final fields. As far as I can tell, the only way to work around it is to use a non-final field - so, just a `private` field, and the `@Getter` annotation, instead of `@Data` or `@Value`.

Curious, what do you think we should do here? Here are the options as I can see them:

1. Rip out the entire "support for `@lombok.Builder.Default`" feature before the `1.8` release.
2. Make it a compilation error to use `@lombok.Builder.Default` on a `final` field.
3. Document this limitation in the ReadMe.
4. Something else?

Let me know what you think!

**Comment by skinny85** [comment]
@alexandrenavarro you previously mentioned you work on a project that uses Jilt with Lombok (in [this comment](https://github.com/skinny85/jilt/issues/28#issuecomment-2628922772)).

Any opinions on what I've raised [here](https://github.com/skinny85/jilt/pull/31#issuecomment-2693328181)?

**Comment by alexandrenavarro** [comment]
I will check this week-end.

**Comment by alexandrenavarro** [comment]
First of all, I will describe generally how I write my objects.

I tried to have objects as immutable as possible.

So my objects are final and the fields are set as final.
I used BigDecimal, BitInteger, String or Immutable objects I created.
I tried to do a copy of list or map in the constructor, not always because I need to redefine the constructor to do it.
I annotated correctly the field or constructor or method with `@Nullable` to use nullaway in order to check potential NPE at compile time.

If all fields are optional, I use @lombok.Builder because I do not need to declare the builder() method and can set `@AllArgsConstructor(access = AccessLevel.PRIVATE) `easily.
If one field is mandatory or defaultable, I use `@jilt.Builder(style = BuilderStyle.STAGED, factoryMethod = "builder") `because it forces me to have mandatory fields not set to null contrary to lombok. I just add the builder() method in the class.
If I want to create an object with 2 fields, I used a method like `MyObject.valueOf(arg1, arg2);`
If I want to create an object with 3 fields or more, I used the `builder()` method, like `MyObject.builder().field1("field1").field2("field2").field3("field3").build();`
I always type first the object to create the object fluently in my IDE.

On the annotation processor, I always set Lombok first and then the other like jilt because generally they depend on the Lombok processors. In maven or gradle, the order of the declaration should be used to define which one will be processed first. So I don't understand your point on 

> you cannot specify which order annotation processors run

My objects are generally annotated with

```
@AllArgsConstructor(access = AccessLevel.PACKAGE)
@Getter
@EqualsAndHashCode(callSuper = false)
@ToString
@Builder(style = BuilderStyle.STAGED, factoryMethod = "builder")
```

I used notably `@AllArgsConstructor(access = AccessLevel.PACKAGE).`I set a package not private just because you have to write boilerplate code when you use jilt. I considered you should not use the package method/constructor only if you are in your lib/code. If you use it outside of the lib by setting a class in the same package, you are searching for problems, and if you have problems, it is your fault. Maybe if I write an external api, I will write as a private constructor with some boilerplate code but for my own objects, I consider I have to write too much boilerplate code compared to the safety it guarantees. The private/package constructor is used in the builder but also through the spring controllers which can use the private / package constructor to create the object (thought reflection hack) and then can validate with bean-validation lib and verify if all the field are correct notably the mandatory in the requestBody parameter object.

Finally, for defaulted field, I don't use `@Builder.Default `from Lombok because of 2 reasons :

1. if you create an object from Builder, the defaulted field is done but if you create with a constructor, it is not. To fix it, you can set the constructor as private but I had the bug once.
2. it is linked to the `@Nullable` annotation. For a defaulted field, you must not have `@Nullable` on field because it will always be set but you must have `@Nullable` on the constructor if you use nullaway. But you can not do that with the `@AllArgsConstructor`, it will always copy the annotations of the fields in the constructor which is 95% true but no in this use case. 

If I don't have a lot of fields, I create a custom constructor with correct `@Nullable` on the different parameter notably on the defaulteable fields, the constructor will be annotated with `@Builder` and I default the defaultable fields inside the constructor.

If I have a lot of fields, l created with `@AllArgsConstructor(access = AccessLevel.PRIVATE) `and create a custom constructor with a `@Builder` with correct `@Nullable `on the different parameter notably on the defaulteable fields, I default the default fields in the constructor and call `this(x, y ...);`.
These 2 solutions work but they are not as simple as the @Builder.Default, more code, and each time you add a field, It will not compile, you have to fix it but it is easy to fix and you will not have any runtime exception you can not see at compile time.

Maybe one solution is to create a `@jilt.Default`. Use it on a defaultable field with a string field with the code of the initialization of the field like `@jilt.Default(value="42")`. You can set some code like defensive copy in the value for map/list for instance or basic initialization.
Jilt checks if they are public constructors when there is any `@jilt.Default`, if it is the case, there is a compilation error. The defaulting will be done in the builder and you have to consider in the StagedBulder the defaulteable field as optional and set the field with the value of `@jilt.Default` if it is not set by the client before calling the private / package constructor.
Nevertheless, I'm not a big fan of having initializer code in a string in the annotation but I do not see a better simple solution and if you do wrong, you will have some compilation errors, so I think it can be acceptable.

What do you think @MehrunesSky @skinny85  about the potential solution? 
Maybe there is a better solution derived from this solution notably on how to explain how to initialize the defaulted field.

I hope it is clear and it can help.
Don't hesitate to reply if you have any questions or comments.

**Comment by skinny85** [comment]
Thanks for the explanation @alexandrenavarro! A few points:

 
> On the annotation processor, I always set Lombok first and then the other like jilt because generally they depend on the Lombok processors. In maven or gradle, the order of the declaration should be used to define which one will be processed first. So I don't understand your point on
> 
> > you cannot specify which order annotation processors run

I don't think that works. See specifically [this SO answer](https://stackoverflow.com/a/29235021):

> After a lot of research and having talked to one of the Lombok developers, it turns out that because javac does class loading based on hashCode(), the order of annotation processors running in this scenario is essentially random.

------

> If I have a lot of fields, l created with `@AllArgsConstructor(access = AccessLevel.PRIVATE) `and create a custom constructor with a `@Builder` with correct `@Nullable `on the different parameter notably on the defaulteable fields, I default the default fields in the constructor and call `this(x, y ...);`. These 2 solutions work but they are not as simple as the @Builder.Default, more code, and each time you add a field, It will not compile, you have to fix it but it is easy to fix and you will not have any runtime exception you can not see at compile time.

How does that work - don't the two constructors clash with each other, since they have the same signature?
 
> Jilt checks if they are public constructors when there is any `@jilt.Default`, if it is the case, there is a compilation error. 

Why would that be a compilation error? The entire point of this feature is to be able to use it with `@AllArgsConstructor`. I'm not sure I understand why would you error out in that case?

**Comment by alexandrenavarro** [comment]
On the annotation processors, I remembered I had an issue if I do not specify lombok before jilt as annotation dependencies in gradle (when jilt tries to see getters of the object). I specified the right order with always lombok first and it solves my issue (maybe by chance?). Maybe there are some other issues linked to random processor annotation order,  I thought your problem was linked but maybe not.

> How does that work - don't the two constructors clash with each other, since they have the same signature?

You are right, I made a mistake. 
Another solution when you have a lot of fields not really beautiful is 
- to annotate your object with `@AllArgsConstructor(access = AccessLevel.PRIVATE) `
- then delombok with intellij
- add @Nullable on defaultable arguments
- default in the constructor the defautable fields when they are null.

It is quick to write even if you have a lot of fields but each time you add a field, it will not compile, you have to update your constructor but it is not really error prone.

> Why would that be a compilation error? The entire point of this feature is to be able to use it with @AllArgsConstructor. I'm not sure I understand why would you error out in that case?

The reason why I ask that is to force the user to use the builder not the constructor because in my point of view, it is error prone like the `@Builder.Default` in lombok, the defaultable fields will be not default if you call directly the constructor contrary to the builder.

After thinking, the solution I proposed is not totally safe because as you can have problem with spring controllers. By default, it will use the private constructor without the defaulting for deserialization. You can imagine force to use a specific Builder also `@JsonDeserialize(builder=Foobar.FoobarBuilder[Impl].class)` to solve it but not sure it will work with jilt staged builder (I don't think it works, to be tested).
On jdk, they are working on serialization 2.0 [Serialization : the new Hope](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://www.youtube.com/watch%3Fv%3DfbqAyRJoQO0&ved=2ahUKEwjWmq2U2IKMAxUHRqQEHWMNIEUQwqsBegQIChAG&usg=AOvVaw3TInivjSRpNbyHF8X008Yd ) and the main idea is to have only one annotated method/constructor to serialize/deserialize object with defaulting and validation.

So finally, I'm shared on the solution I proposed and I don't really see any good solution.

In my opinion, the less ugly and safe is to annotate your object with `@AllArgsConstructor(access = AccessLevel.PRIVATE) ` then delombok with intellij, and add `@Nullable` on defaultable argument and default in the constructor the defaultable fields when they are null but when you want to add a field you have to update your constructor.

**Comment by skinny85** [comment]
Thanks @alexandrenavarro. I agree with your assessment. For that reason, unless you object @MehrunesSky, I'll revert this PR before the `1.8` release, since I want to include the Gradle incremental changes from issue #35. We can always bring it back later if we decide this is still something we want to do.
